### ISSUE TITLE
the file named "data/semanticKITTI/sequences/%s/velodyne/%s.bin"  can not be found 

### ISSUE THREAD

**Issue by sunjc0306** [ecr23xx/icp-cuda-pytorch-extension#1]
Thanks for your code that can be used for the ICP algorithm.
I do not know what is the file named "data/semanticKITTI/sequences/%s/velodyne/%s.bin"?
Can you tell me about some details? 
Otherwise, how to achieve ICP alignment of two mesh files?

**Comment by ecr23xx** [comment]
The file name is from semantic KITTI dataset. To align two mesh files, you should directly call "icp_pytorch"
