### ISSUE TITLE
Erros in the code

### ISSUE THREAD

**Issue by DavidBoja** [ecr23xx/icp-cuda-pytorch-extension#2]
Hi,

The distances returned by the nn_search 
https://github.com/ecr23xx/icp-cuda-pytorch-extension/blob/669cf8884d5b637ebd2fc4095d10216b25c69429/layers.py#L27
are squared. They should be rooted with  `torch.sqrt(dist)` to be real L2 norm distances.

Also, the rotation matrix for obtaining the translation:
https://github.com/ecr23xx/icp-cuda-pytorch-extension/blob/669cf8884d5b637ebd2fc4095d10216b25c69429/layers.py#L42

should be transposed.

**Comment by ecr23xx** [comment]
Thanks for that! Would you like to send a pull request to fix these problems?
